version: '3.4'

services:
  transactionstestapi:
    image: ${DOCKER_REGISTRY-}transactionstestapi
    build:
      context: .
      dockerfile: TransactionsTestApi/Dockerfile

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=testproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    ports:
      - 5432:5432